// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package notifications

import (
	"database/sql"
)

type Notification struct {
	ID        int64
	TaskID    int64
	Message   string
	IsRead    sql.NullBool
	CreatedAt sql.NullTime
}
